language: node_js

sudo: required

services:
    - docker

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8

before_install:
  - export CXX="g++-4.8"
  - docker pull opower/opentsdb
  - docker run -d -p 127.0.0.1:4242:4242 --name opentsdb opower/opentsdb
  - docker ps -a

node_js:
    - '4.2'

before_script:
    - npm install juttle@^0.5.0

script:
    - npm run test-coverage
    - npm run check-coverage
